In [98]:
import numpy as np
import pandas as pd
import math as m
from einops import rearrange, repeat
import os
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
import torch.optim as optim
from tqdm import tqdm


### Preperation (NOTE: Using meter as unit)

In [99]:
# Utility functions
# convert pointcloud from cartisean coordinate to spherical coordinate
def cart2sph(xyz):
    x = xyz[:,0]
    y = xyz[:,1]
    z = xyz[:,2]
    XsqPlusYsq = x**2 + y**2
    r = np.sqrt(list(XsqPlusYsq + z**2))
    elev = np.arctan2(list(z), np.sqrt(list(XsqPlusYsq)))
    pan = np.arctan2(list(x), list(y))

    output = np.array([r, elev, pan])
    return rearrange(output, 'a b -> b a') #take transpose

In [100]:
def loadData():
    # Specify the directory path
    dataset_path = 'datasets/testing1'

    # List all files in the specified path, ignoring directories
    files = [f for f in os.listdir(dataset_path) if os.path.isfile(os.path.join(dataset_path, f))]
    files.sort()

    # read the files
    points_xyz = []
    for s in files:
        path = 'datasets/testing1/' + s
        df = pd.read_csv(path)
        a = df.to_numpy()
        points_xyz.append(a[:,8:11])
    return points_xyz

def prepareData(points_xyz):
    # Find the fiew direction of each points:
    # NOTE: points in spherical coordinate are arranged: [r, elev, pan]
    points_sphere = []
    for points in points_xyz:
        points_sphere.append(cart2sph(points))

    ### Process the data
    # Translation vectors for points in each view, we are using camera centre at first frame as origin of world coordinate
    # NOTE: translation vectors below are found by assuming transformation between frames are translations, and obatined by manually finding corrspondance
    # They are translation of the same corrspondance across different frames
    # HARD CODED HERE
    t0 = np.array([0,0,0])
    t1 = np.array([-0.671,-0.016,0.215])
    t2 = np.array([-1.825,-0.091,0.147])
    t3 = np.array([-2.661,-0.263,0.166])
    t4 = np.array([-3.607,-0.156,0.039])
    translations = [t0, t1, t2, t3, t4]

    # camera centre locations
    centres = [-t for t in translations]
    centres_data = []
    for i,c in enumerate(centres):
        l = len(points_sphere[i])
        temp = np.tile(c, (l, 1))
        centres_data.append(temp)

    # stack the points into one big matrix
    stacked = []
    for i in range(len(points_sphere)):
        temp = np.hstack((points_sphere[i], centres_data[i]))
        stacked.append(temp)

    dataset = np.array([])
    for i in range(len(stacked)):
        if i == 0:
            dataset = stacked[i]
        else:
            dataset = np.vstack((dataset, stacked[i]))
    np.random.shuffle(dataset)

    # Mid pass filter, for distance value between 2 and 50 meter
    mask1 = dataset[:,0] > 2
    dataset = dataset[mask1]
    mask2 = dataset[:,0] < 50
    dataset = dataset[mask2]

    return dataset

In [101]:
class LiDAR_NeRF(nn.Module):
    def __init__(self, embedding_dim_pos = 10, embedding_dim_dir = 4, hidden_dim = 256, device = 'cuda'):
        super(LiDAR_NeRF, self).__init__()
        self.device = device
        self.embedding_dim_dir = embedding_dim_dir
        self.embedding_dim_pos = embedding_dim_pos
        self.block1 = nn.Sequential(
            nn.Linear(embedding_dim_pos * 6 + 3 + embedding_dim_dir * 4 + 2, hidden_dim), nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim), nn.ReLU(),               
            nn.Linear(hidden_dim, hidden_dim), nn.ReLU(),               
            nn.Linear(hidden_dim, hidden_dim), nn.ReLU(),               
        )
        
        self.block2 = nn.Sequential(
            nn.Linear(embedding_dim_pos * 6 + 3 + embedding_dim_dir * 4 + 2 + hidden_dim, hidden_dim), nn.ReLU(),               
            nn.Linear(hidden_dim, hidden_dim), nn.ReLU(),               
            nn.Linear(hidden_dim, hidden_dim), nn.ReLU(),               
            nn.Linear(hidden_dim, hidden_dim), nn.ReLU(),
            nn.Linear(hidden_dim,1)
        )
        
    @staticmethod
    def positional_encoding(x, L):
        out = [x]
        for j in range(L):
            out.append(torch.sin(2 ** j * x))
            out.append(torch.cos(2 ** j * x))
        return torch.cat(out, dim=1)

    def forward(self, o, d):
        emb_x = self.positional_encoding(o, self.embedding_dim_pos)
        emb_d = self.positional_encoding(d, self.embedding_dim_dir)
        input = torch.hstack((emb_x,emb_d)).to(dtype=torch.float32)
        temp = self.block1(input)
        input2 = torch.hstack((temp, input)).to(dtype=torch.float32) # add skip input
        output = self.block2(input2)
        return output

In [102]:
def lossBCE(rendered_value, actual_value): 
    loss_bce = nn.CrossEntropyLoss()
    loss = loss_bce(rendered_value, actual_value)
    return loss

In [103]:
def get_sample_positions(origins, angles, near = 3, far = 100, num_bins = 100, device = 'cpu'):
    elev = angles[:,0]
    pan = angles[:,1]
    dir_x = torch.tensor(np.cos(elev)*np.cos(pan))
    dir_y = torch.tensor(np.cos(elev)*np.sin(pan))
    dir_z = torch.tensor(np.sin(elev))

    # create a list of magnitudes with even spacing
    t = torch.linspace(near, far, num_bins, device=device).expand(dir_x.shape[0], num_bins)  # [batch_size, num_bins]
    
    # preterb the spacing
    mid = (t[:, :-1] + t[:, 1:]) / 2.
    lower = torch.cat((t[:, :1], mid), -1)
    upper = torch.cat((mid, t[:, -1:]), -1)
    u = torch.rand(t.shape, device = device)
    t = lower + (upper - lower) * u  # [batch_size, nb_bins]
    
    # convert magnitudes into positions by multiplying unit vector in each direction
    t = rearrange(t, 'a b -> b a')  # [num_bins, batch_size]
    pos_x = dir_x*t     # [num_bins, batch_size]
    pos_y = dir_y*t
    pos_z = dir_z*t
    multiplied = rearrange([pos_x,pos_y,pos_z], 'c b n  -> (n b) c')   # [num_bin*batchsize, 3]
    # tile the origin values
    origins_tiled = repeat(origins, 'n c -> (n b) c', b = num_bins) # [num_bin*batch_size, 3]
    pos = torch.tensor(origins_tiled) + multiplied
    # tile the angle for convenience
    angles_tiled = torch.tensor(repeat(angles, 'n c -> (n b) c', b = num_bins))
    return pos, angles_tiled



In [104]:
# returns pytorch tensor of sigmoid of projected SDF
def get_actual_value(sample_positions, gt_distance, num_bins=100):
    # tile distances
    gt_distance_tiled = repeat(gt_distance, 'b -> (b n) 1', n=num_bins)
    # calculate distance from sample_position
    temp = torch.tensor(sample_positions**2)
    pos_distance = torch.sqrt(torch.sum(temp, dim=1, keepdim=True ))

    # print(pos_distance[0:100])
    # find the "projected" value
    sigmoid = nn.Sigmoid()
    values = sigmoid(-(pos_distance - gt_distance_tiled))

    return values

In [105]:
with torch.no_grad():
    sigmoid = nn.Sigmoid()
    pos_distance = torch.tensor(100)
    gt_distance = torch.tensor(100) 
    value = sigmoid(-(pos_distance- gt_distance))
    print(value)

tensor(0.5000)


In [ ]:
# sample data for testing
points = loadData()
dataset = prepareData(points)
test_batch = dataset[128:256,:]
device = 'cpu'
ground_truth_distance = test_batch[:,0]
angles = test_batch[:,1:3]
origin = test_batch[:,3:]
pos, ang = get_sample_positions(origin, angles,num_bins=100)

model = LiDAR_NeRF(hidden_dim=256)
rendered = model(pos, ang)
sigmoid = nn.Sigmoid()
rendered_sigmoid = sigmoid(rendered)
# temp = torch.zeros_like(pos)
val = (get_actual_value(pos, ground_truth_distance)).to(dtype = torch.float32)


for x in val:
    print(x)
# print(min(rendered))
# loss_bce = nn.BCELoss()
# loss = loss_bce(rendered_sigmoid, val)
# print(loss)

In [41]:
def train(model, optimizer, scheduler, dataloader, device = 'cpu', epoch = int(1e5), num_bins = 100):
    training_losses = []
    for _ in tqdm(range(epoch)):
        for batch in dataloader:
            # parse the batch
            ground_truth_distance = batch[:,0]
            angles = batch[:,1:3]
            origin = batch[:,:3:7]
            
            sample_positions, sample_angles = get_sample_positions(origin, angles, num_bins=num_bins)
            
            rendered_value = model(sample_positions.to(device), sample_angles.to(device))
            sigmoid = nn.Sigmoid()
            rendered_value_sigmoid = sigmoid(rendered_value - ground_truth_distance)
            actual_value_sigmoided = (get_actual_value(sample_positions.to(device), ground_truth_distance.to(device))).to(dtype = torch.float32)
            
            # loss = lossBCE(rendered_value, actual_value_sigmoided)  # + lossEikonal(model)
            # loss_bce = nn.CrossEntropyLoss()
            loss_bce = nn.BCELoss()
            loss = loss_bce(rendered_value_sigmoid, actual_value_sigmoided)
            # BCEWithLogitsLoss
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            training_losses.append(loss.item())
            # print(loss.item())
            print(loss.item())
        scheduler.step()
    return training_losses
    

In [117]:
loss = nn.BCELoss()
a = torch.tensor([0.999], dtype=torch.float32)
b = torch.tensor([1], dtype=torch.float32)
c = loss(a,b)
c

tensor(0.0010)

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using {device} device")
points = loadData()
print("loaded data")
data_matrix = prepareData(points)
print("prepared data")
training_dataset = torch.from_numpy(data_matrix)
data_loader = DataLoader(training_dataset, batch_size=1024, shuffle = True)
model = LiDAR_NeRF(hidden_dim=512, embedding_dim_dir=10, device = device).to(device)
optimizer = torch.optim.Adam(model.parameters(),lr=5e-4)
scheduler = torch.optim.lr_scheduler.MultiStepLR(optimizer, milestones=[2, 4, 8, 16], gamma=0.5)
losses = train(model, optimizer, scheduler, data_loader, epoch = 20, device=device)


In [13]:
### Save the model
torch.save(model.state_dict(), 'version1_trial1.pth')

In [ ]:
#### Load the model and try to "visualize" the model's datapoints
model2 = LiDAR_NeRF(hidden_dim=512, embedding_dim_dir=10, device = device)
model2.load_state_dict(torch.load('/home/ansonhon/anson/thesis/LiDAR_NeRF/local/models/version1_trial1.pth'))
model2.eval()  # Set the model to inference mode

In [109]:
#### Prepare query points
positions_tensor = torch.zeros((100000,3))
directions = np.zeros((100000,2))
idx = 0
for i in range(1000):
    for j in range(100):
        ele_ang = -np.pi/4 + (np.pi/400)*j
        pan_ang = np.pi*2 * (i/1000)
        directions[idx,0] = ele_ang
        directions[idx,1] = pan_ang
        idx += 1
directions_tensor = torch.tensor(directions)

In [96]:
# position = torch.tensor([[0,0,0],[0,0,0]])
# direction = torch.tensor([[-0.001,0],[0,0]])
with torch.no_grad():
    output = model2(positions_tensor, directions_tensor)

In [97]:
for x in output:
    print(x)

tensor([3.3547])
tensor([3.1934])
tensor([2.4782])
tensor([2.4223])
tensor([2.9079])
tensor([2.1109])
tensor([1.2940])
tensor([1.1857])
tensor([0.3016])
tensor([0.1648])
tensor([0.6015])
tensor([0.0919])
tensor([-0.1016])
tensor([-0.3935])
tensor([-0.6098])
tensor([-0.5161])
tensor([-0.5886])
tensor([-0.5813])
tensor([-0.4015])
tensor([-0.5700])
tensor([-0.6950])
tensor([-0.5777])
tensor([-0.7237])
tensor([-0.6062])
tensor([-0.6214])
tensor([-0.8526])
tensor([-0.9488])
tensor([-1.1688])
tensor([-1.2470])
tensor([-1.0719])
tensor([-1.1734])
tensor([-1.1340])
tensor([-1.1512])
tensor([-1.3062])
tensor([-1.3207])
tensor([-1.2513])
tensor([-1.3668])
tensor([-1.2816])
tensor([-1.1844])
tensor([-1.2934])
tensor([-1.2731])
tensor([-1.1526])
tensor([-1.1415])
tensor([-0.9868])
tensor([-0.9948])
tensor([-0.8785])
tensor([-0.8788])
tensor([-0.9802])
tensor([-0.8248])
tensor([-0.8170])
tensor([-0.9919])
tensor([-1.0999])
tensor([-1.3594])
tensor([-1.4524])
tensor([-1.3909])
tensor([-1.5380])
tens